version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - db
    environment:
      JWT_SECRET: "cestpourlasciencemerciderestercourtoi"
      REFRESH_TOKEN_SECRET: "jesensquelesemmerdesvontcommenceraveccettehistoirederefreshtokentoutcapoursetaperundauprojet"
      PORT: 3005
      DB_NAME: "kittydelivery"
      DB_ID_NAME: "postgres"
      DB_ID_PASSWORD: "admin"
      DB_HOST: "db"
      DB_DIALECT: "postgres"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: kittydelivery
